### ISSUE TITLE
No tweets in weetwit buffer

### ISSUE THREAD

**Issue by Shir0kamii** [ainmosni/weetwit#21]
Hi,

I followed the installation steps and authenticated myself, but no tweet appears in the weetwit buffer. It may come from the error I get when reloading the script : 

```
python: loading script "/home/shir0kamii/.weechat/python/weetwit.py"
python: stdout/stderr: /usr/lib/python2.7/dist-packages/cffi/vengine_cpy.py:177: UserWarning: reimporting '_Cryptography_cffi_36a40ff0x2bad1bae' might overwrite older definitions
python: stdout/stderr:   % (self.verifier.get_module_name()))
python: registered script "weetwit", version 0.10.3 (Full twitter suite for Weechat.)
```

The strange thing is that I can send tweets, but nothing will appear in the buffer.

Do you have any clue about what to do ?

**Comment by Shir0kamii** [comment]
@ainmosni Are you still maintaining it ?

**Comment by ainmosni** [comment]
@Shir0kamii I am but I recently moved and I have no internet at home yet so I can't really patch it. Can you try to run timelined seperately with `/usr/bin/python /usr/local/bin/timelined ~/.weechat/weetwit/` and see what happens?

**Comment by Shir0kamii** [comment]
Sorry for the delay,

When I try it, I've got no output at all. What am I supposed to see ?

I will try to narrow down the problem this weekend or the next, looking at the code. If you're willing to wait a bit, I'll stay you tuned.
